# Cloudbuild pipeline for a build with an image
# that passes the Scorecard attestation policy
# To run manually, log into GCP and run:
# cd 
steps:
  # Build a 'good' image. In this case, build the attestor attests to its own image
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.',
      '-t', 'gcr.io/$PROJECT_ID/scorecard-attestor:latest',
      '-f', 'Attestor.dockerfile']
  - id: 'Push image'
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
    - -c
    - |
      docker push gcr.io/$PROJECT_ID/scorecard-attestor:latest &&
      docker image inspect gcr.io/$PROJECT_ID/scorecard-attestor:latest --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
  - id: 'Attest to image'
    name: "gcr.io/$PROJECT_ID/scorecard-attestor:latest"
    secretEnv:
    - GITHUB_AUTH_TOKEN
    entrypoint: /bin/bash
    args:
      - -c
      - '/scorecard-attestor attest --image=$(cat image-digest.txt) --note-name projects/$PROJECT_ID/notes/scorecard-attestor-note --policy=gs://scorecard-binauthz-test/policy-binauthz.yaml --repo-url https://github.com/ossf/scorecard --kms-key-name=projects/$PROJECT_ID/locations/global/keyRings/kritis-signer-key-ring/cryptoKeys/kritis-signer-key/cryptoKeyVersions/1 --kms-digest-alg=SHA256'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-auth-token/versions/latest
      env: GITHUB_AUTH_TOKEN